[package]
name = "db-exp"
version = "0.1.0"
authors = ["João Paulo Pulga <joaopaulo1339@outlook.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.18"
env_logger = "0.6.0"
tera = "0.11.20"
sqlite = "0.24.0"
serde_derive = "1.0.84"
serde="1.0.84"